import type { AaliyahAtomicRegistry } from "./registry-types.js";

export const AALIYAH_ATOMIC_REGISTRY: AaliyahAtomicRegistry = {
  registryVersion: "2026-03-12.aaliyah.v1",
  constitutionVersion: "aaliyah_safety_constitution_v1",
  items: [
    {
      agentId: "aaliyah",
      displayName: "Aaliyah",
      parentLayer: "aaliyah-control",
      exactAtomicTaskId: "executive_orchestration_founder_protection",
      exactAtomicTask: "Perform executive orchestration and founder protection only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: [
        "founder requests requiring triage",
        "incoming work requiring specialist routing",
        "calendar and communication interruptions needing orchestration"
      ],
      allowedOutputContract: [
        "routing instructions",
        "escalation decisions",
        "founder-protection summaries"
      ],
      forbiddenScope: [
        "specialist execution",
        "email drafting",
        "dispatching approved drafts",
        "policy override",
        "memory boundary override"
      ],
      escalationTriggers: [
        "sensitive principal request without clear owner",
        "workflow crossing company or mode boundary",
        "policy conflict between lanes"
      ],
      fallbackBehavior: "Fail closed, protect the principal, and route to the correct specialist or executive owner.",
      approvalClass: "orchestration_only",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["receptionist", "executive_assistant"]
    },
    {
      agentId: "aaliyah-thread-normalizer",
      displayName: "Aaliyah Thread Normalizer",
      parentLayer: "aaliyah-email-runtime",
      exactAtomicTaskId: "email_thread_normalization",
      exactAtomicTask: "Normalize inbound email threads into the canonical email thread model only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["raw connector thread payloads", "account metadata", "normalization config"],
      allowedOutputContract: ["normalized email thread records"],
      forbiddenScope: ["intent classification", "routing", "draft composition", "dispatch"],
      escalationTriggers: ["unparseable connector payload", "missing sender metadata", "thread payload integrity mismatch"],
      fallbackBehavior: "Reject malformed payloads and emit a normalization failure for incident handling.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["email_drafting"]
    },
    {
      agentId: "aaliyah-intent-classifier",
      displayName: "Aaliyah Intent Classifier",
      parentLayer: "aaliyah-email-runtime",
      exactAtomicTaskId: "email_intent_classification",
      exactAtomicTask: "Classify normalized email threads into one intent category only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["normalized email thread records", "classification rules"],
      allowedOutputContract: ["email intent category decisions"],
      forbiddenScope: ["priority scoring", "risk scoring", "routing", "draft composition", "dispatch"],
      escalationTriggers: ["conflicting intent indicators", "legal or sensitive content ambiguity"],
      fallbackBehavior: "Return no intent decision and force escalation for human review.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["email_drafting"]
    },
    {
      agentId: "aaliyah-urgency-scorer",
      displayName: "Aaliyah Urgency Scorer",
      parentLayer: "aaliyah-email-runtime",
      exactAtomicTaskId: "email_urgency_scoring",
      exactAtomicTask: "Score the urgency level of a classified email thread only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["classified email threads", "urgency rules"],
      allowedOutputContract: ["email priority assignments"],
      forbiddenScope: ["intent classification", "risk scoring", "routing", "draft composition"],
      escalationTriggers: ["priority indicators conflict", "principal interrupt risk exceeds threshold"],
      fallbackBehavior: "Set conservative priority and require review by the escalation decision agent.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["email_drafting"]
    },
    {
      agentId: "aaliyah-risk-scorer",
      displayName: "Aaliyah Risk Scorer",
      parentLayer: "aaliyah-email-runtime",
      exactAtomicTaskId: "email_risk_scoring",
      exactAtomicTask: "Score the operational and reputational risk of a classified email thread only.",
      owningExecutiveId: "cso",
      owningDepartmentId: "strategy-security-risk",
      allowedInputContract: ["classified email threads", "risk rules"],
      allowedOutputContract: ["email risk level assignments"],
      forbiddenScope: ["draft composition", "dispatch", "policy override", "ownership resolution"],
      escalationTriggers: ["legal or sensitive content", "high-risk commitment language", "principal safety exposure"],
      fallbackBehavior: "Mark the thread high-risk and require escalation instead of proceeding automatically.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-company-mode-resolver",
      displayName: "Aaliyah Company Mode Resolver",
      parentLayer: "aaliyah-control",
      exactAtomicTaskId: "email_company_mode_resolution",
      exactAtomicTask: "Resolve the active company and operating mode for an inbound email workflow only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["normalized email threads", "account metadata", "mode rules"],
      allowedOutputContract: ["company visibility decisions", "mode visibility decisions"],
      forbiddenScope: ["routing", "draft composition", "dispatch", "memory override"],
      escalationTriggers: ["cross-company ambiguity", "mode conflict with account configuration"],
      fallbackBehavior: "Block processing and escalate rather than leak work across company or mode boundaries.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["receptionist", "executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-contact-tier-assigner",
      displayName: "Aaliyah Contact Tier Assigner",
      parentLayer: "aaliyah-email-runtime",
      exactAtomicTaskId: "email_contact_tier_assignment",
      exactAtomicTask: "Assign contact tier for an email thread participant only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["normalized email threads", "contact metadata", "tiering rules"],
      allowedOutputContract: ["contact tier assignments"],
      forbiddenScope: ["intent classification", "routing", "dispatch", "review status transitions"],
      escalationTriggers: ["unknown high-value sender", "principal-tier contact uncertainty"],
      fallbackBehavior: "Default to conservative tiering and require review for sensitive handling.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-ownership-resolver",
      displayName: "Aaliyah Ownership Resolver",
      parentLayer: "aaliyah-control",
      exactAtomicTaskId: "email_ownership_resolution",
      exactAtomicTask: "Resolve the owning specialist lane for an email thread only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["classified email threads", "org routing context", "company mode decisions"],
      allowedOutputContract: ["email routing resolutions"],
      forbiddenScope: ["draft composition", "dispatch", "review actions", "policy override"],
      escalationTriggers: ["unsupported intent category", "ambiguous specialist ownership"],
      fallbackBehavior: "Fail closed and route to escalation instead of guessing ownership.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-approval-requirement-decider",
      displayName: "Aaliyah Approval Requirement Decider",
      parentLayer: "aaliyah-safety",
      exactAtomicTaskId: "email_approval_requirement_decision",
      exactAtomicTask: "Determine whether a processed email draft requires approval only.",
      owningExecutiveId: "cso",
      owningDepartmentId: "strategy-security-risk",
      allowedInputContract: ["classified email threads", "risk scores", "policy rules"],
      allowedOutputContract: ["approval requirement decisions"],
      forbiddenScope: ["draft composition", "dispatch", "review status transitions", "route ownership changes"],
      escalationTriggers: ["policy gap on sensitive content", "approval requirement conflict"],
      fallbackBehavior: "Require approval by default when policy conditions are unclear.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["email_drafting"]
    },
    {
      agentId: "aaliyah-escalation-decider",
      displayName: "Aaliyah Escalation Decider",
      parentLayer: "aaliyah-safety",
      exactAtomicTaskId: "email_escalation_decision",
      exactAtomicTask: "Decide whether a processed email thread must be escalated only.",
      owningExecutiveId: "cso",
      owningDepartmentId: "strategy-security-risk",
      allowedInputContract: ["classified email threads", "priority scores", "risk scores", "policy rules"],
      allowedOutputContract: ["escalation decisions"],
      forbiddenScope: ["draft composition", "dispatch", "ownership resolution", "review approval"],
      escalationTriggers: ["principal exposure", "legal sensitivity", "high-risk commitments"],
      fallbackBehavior: "Escalate instead of continuing when the thread cannot be handled safely.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-interrupt-classifier",
      displayName: "Aaliyah Interrupt Classifier",
      parentLayer: "aaliyah-control",
      exactAtomicTaskId: "email_interrupt_classification",
      exactAtomicTask: "Classify whether an email thread is a founder or executive interrupt only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["classified email threads", "priority scores", "contact tiers"],
      allowedOutputContract: ["interrupt classifications"],
      forbiddenScope: ["draft composition", "dispatch", "routing ownership changes", "approval decisions"],
      escalationTriggers: ["possible founder interrupt", "uncertain executive access rule"],
      fallbackBehavior: "Treat as interrupt-risk and escalate to orchestration for founder protection.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["receptionist", "executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-draft-composer",
      displayName: "Aaliyah Draft Composer",
      parentLayer: "aaliyah-email-runtime",
      exactAtomicTaskId: "email_draft_composition",
      exactAtomicTask: "Compose draft-only reply suggestions for safe email workflows only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["classified email threads", "routing resolutions", "prompt assembly payloads"],
      allowedOutputContract: ["email draft suggestions"],
      forbiddenScope: ["dispatch", "review approval", "ownership resolution", "policy override"],
      escalationTriggers: ["unsafe claim requirement", "missing facts for reply", "sensitive commitment language"],
      fallbackBehavior: "Produce a safe escalation-oriented draft and block any implied completion claim.",
      approvalClass: "always_required",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["email_drafting"]
    },
    {
      agentId: "aaliyah-review-item-creator",
      displayName: "Aaliyah Review Item Creator",
      parentLayer: "aaliyah-email-runtime",
      exactAtomicTaskId: "email_review_item_creation",
      exactAtomicTask: "Create review queue items from generated drafts only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["email draft suggestions", "assignment provenance", "run provenance"],
      allowedOutputContract: ["draft review records"],
      forbiddenScope: ["review approval", "dispatch", "draft composition", "routing changes"],
      escalationTriggers: ["missing draft provenance", "review queue persistence failure"],
      fallbackBehavior: "Fail the processing run and surface an operational incident rather than lose review provenance.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["email_drafting"]
    },
    {
      agentId: "aaliyah-review-state-manager",
      displayName: "Aaliyah Review State Manager",
      parentLayer: "aaliyah-email-runtime",
      exactAtomicTaskId: "email_review_status_transition",
      exactAtomicTask: "Apply governed review status transitions for draft review items only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["draft review items", "review action requests"],
      allowedOutputContract: ["updated draft review statuses"],
      forbiddenScope: ["dispatch", "draft composition", "routing changes", "approval policy changes"],
      escalationTriggers: ["invalid review transition", "missing reviewer context", "review provenance mismatch"],
      fallbackBehavior: "Reject invalid transitions and preserve the last valid review state.",
      approvalClass: "operator_action_required",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["email_drafting"]
    },
    {
      agentId: "aaliyah-dispatch-eligibility-validator",
      displayName: "Aaliyah Dispatch Eligibility Validator",
      parentLayer: "aaliyah-safety",
      exactAtomicTaskId: "email_dispatch_eligibility_validation",
      exactAtomicTask: "Validate whether an approved draft is eligible for dispatch only.",
      owningExecutiveId: "cso",
      owningDepartmentId: "strategy-security-risk",
      allowedInputContract: ["approved review items", "account connection metadata", "dispatch policy rules"],
      allowedOutputContract: ["dispatch policy decisions"],
      forbiddenScope: ["sending email", "draft composition", "review approval", "account mutation"],
      escalationTriggers: ["protected category dispatch attempt", "account safety policy mismatch", "high-risk send request"],
      fallbackBehavior: "Block dispatch and require operator intervention when policy safety cannot be proven.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["email_drafting"]
    },
    {
      agentId: "aaliyah-approved-draft-dispatcher",
      displayName: "Aaliyah Approved Draft Dispatcher",
      parentLayer: "aaliyah-email-runtime",
      exactAtomicTaskId: "email_approved_draft_dispatch",
      exactAtomicTask: "Dispatch already approved and policy-eligible drafts through the configured Gmail connector only.",
      owningExecutiveId: "coo",
      owningDepartmentId: "operations",
      allowedInputContract: ["approved review items", "dispatch policy decisions", "connected Gmail account metadata"],
      allowedOutputContract: ["email dispatch records", "Gmail send result metadata"],
      forbiddenScope: ["draft composition", "review approval", "policy override", "generic send-anything behavior"],
      escalationTriggers: ["connector failure", "account misconfiguration", "Gmail send rejection"],
      fallbackBehavior: "Record a failed dispatch, preserve auditability, and raise an operational incident instead of retrying silently.",
      approvalClass: "operator_action_required",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["email_drafting"]
    },
    {
      agentId: "aaliyah-audit-trace-recorder",
      displayName: "Aaliyah Audit Trace Recorder",
      parentLayer: "aaliyah-safety",
      exactAtomicTaskId: "email_audit_trace_recording",
      exactAtomicTask: "Record audit traces and provenance for email workflow actions only.",
      owningExecutiveId: "cto",
      owningDepartmentId: "technology-engineering",
      allowedInputContract: ["workflow provenance events", "assignment records", "dispatch records"],
      allowedOutputContract: ["audit trace entries"],
      forbiddenScope: ["routing", "draft composition", "dispatch policy decisions", "review approval"],
      escalationTriggers: ["missing provenance linkage", "audit persistence failure"],
      fallbackBehavior: "Fail closed and surface operational failure when audit integrity cannot be preserved.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["receptionist", "executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-policy-compliance-validator",
      displayName: "Aaliyah Policy Compliance Validator",
      parentLayer: "aaliyah-safety",
      exactAtomicTaskId: "email_policy_compliance_validation",
      exactAtomicTask: "Validate email workflow actions against policy only.",
      owningExecutiveId: "cso",
      owningDepartmentId: "strategy-security-risk",
      allowedInputContract: ["email workflow decisions", "policy rules", "risk context"],
      allowedOutputContract: ["policy compliance decisions"],
      forbiddenScope: ["routing", "draft composition", "dispatch", "review state mutation"],
      escalationTriggers: ["policy violation", "missing policy coverage", "cross-lane responsibility breach"],
      fallbackBehavior: "Reject the workflow step and escalate rather than allow undefined policy behavior.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-memory-boundary-enforcer",
      displayName: "Aaliyah Memory Boundary Enforcer",
      parentLayer: "aaliyah-safety",
      exactAtomicTaskId: "email_memory_boundary_enforcement",
      exactAtomicTask: "Enforce memory boundary compliance for Aaliyah workflows only.",
      owningExecutiveId: "cto",
      owningDepartmentId: "technology-engineering",
      allowedInputContract: ["memory access requests", "company visibility rules", "mode visibility rules"],
      allowedOutputContract: ["memory boundary decisions"],
      forbiddenScope: ["draft composition", "routing", "dispatch", "review approval"],
      escalationTriggers: ["cross-company access attempt", "mode boundary violation", "untrusted memory request"],
      fallbackBehavior: "Deny access and require explicit escalation when boundary safety is uncertain.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["receptionist", "executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-scope-drift-detector",
      displayName: "Aaliyah Scope Drift Detector",
      parentLayer: "aaliyah-safety",
      exactAtomicTaskId: "email_scope_drift_detection",
      exactAtomicTask: "Detect when an Aaliyah workflow step drifts outside its declared atomic scope only.",
      owningExecutiveId: "cto",
      owningDepartmentId: "technology-engineering",
      allowedInputContract: ["workflow actions", "atomic registry entries", "policy decisions"],
      allowedOutputContract: ["scope drift findings"],
      forbiddenScope: ["dispatch", "routing", "draft composition", "review approval"],
      escalationTriggers: ["specialist absorption attempt", "multi-verb task creep", "orchestration scope breach"],
      fallbackBehavior: "Block the drifting action and route to the correct specialist or operator path.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["receptionist", "executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-overlap-detector",
      displayName: "Aaliyah Overlap Detector",
      parentLayer: "aaliyah-safety",
      exactAtomicTaskId: "email_overlap_detection",
      exactAtomicTask: "Detect overlapping atomic ownership between Aaliyah workflow agents only.",
      owningExecutiveId: "cto",
      owningDepartmentId: "technology-engineering",
      allowedInputContract: ["atomic registry entries", "workflow definitions", "policy mappings"],
      allowedOutputContract: ["overlap findings"],
      forbiddenScope: ["dispatch", "routing", "draft composition", "review state mutation"],
      escalationTriggers: ["duplicate atomic ownership", "ambiguous task boundary", "conflicting specialist claim"],
      fallbackBehavior: "Fail validation and require registry correction before runtime use.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["receptionist", "executive_assistant", "email_drafting"]
    },
    {
      agentId: "aaliyah-fallback-decider",
      displayName: "Aaliyah Fallback Decider",
      parentLayer: "aaliyah-safety",
      exactAtomicTaskId: "email_fallback_decision",
      exactAtomicTask: "Choose the fallback path for blocked or failed Aaliyah email workflows only.",
      owningExecutiveId: "cso",
      owningDepartmentId: "strategy-security-risk",
      allowedInputContract: ["blocked workflow steps", "incident context", "policy context"],
      allowedOutputContract: ["fallback decisions"],
      forbiddenScope: ["dispatch", "draft composition", "routing ownership changes", "review approval"],
      escalationTriggers: ["no safe continuation path", "repeated workflow failure", "principal-risk fallback"],
      fallbackBehavior: "Escalate to the safest human-controlled path and preserve full audit context.",
      approvalClass: "system_guarded",
      companyVisibility: ["zbestmedia"],
      modeVisibility: ["executive_assistant", "email_drafting"]
    }
  ]
};
